//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_EN
    {
        public Account_EN()
        {
            this.tblFlaggedPostings = new HashSet<FlaggedPosting>();
            this.tblFlaggedPostings1 = new HashSet<FlaggedPosting>();
            this.tblReferrals = new HashSet<Referral>();
        }
    
        public long Account_ENID { get; set; }
        public string UserName { get; set; }
        public long ENID { get; set; }
        public string Name_First { get; set; }
        public string Name_Last { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime PasswordLastReset_DT { get; set; }
        public bool IsMasterYN { get; set; }
        public string ResetCode { get; set; }
        public Nullable<System.DateTime> ResetTimestamp { get; set; }
    
        public virtual EN tblEN { get; set; }
        public virtual ICollection<FlaggedPosting> tblFlaggedPostings { get; set; }
        public virtual ICollection<FlaggedPosting> tblFlaggedPostings1 { get; set; }
        public virtual ICollection<Referral> tblReferrals { get; set; }
    }
}
