//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account_Employer
    {
        public Account_Employer()
        {
            this.tblReferralNotes = new HashSet<ReferralNote>();
        }
    
        public long Account_EmployerID { get; set; }
        public string UserName { get; set; }
        public long PartnerID { get; set; }
        public string Name_First { get; set; }
        public string Name_Last { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public System.DateTime PasswordLastReset_DT { get; set; }
        public bool IsMasterYN { get; set; }
        public string ResetCode { get; set; }
        public Nullable<System.DateTime> ResetTimestamp { get; set; }
    
        public virtual ICollection<ReferralNote> tblReferralNotes { get; set; }
        public virtual Partner tblPartner { get; set; }
    }
}
