//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Audit_Login
    {
        public long Audit_LoginID { get; set; }
        public Nullable<long> AccountID { get; set; }
        public string AccountType { get; set; }
        public string UserNameEntered { get; set; }
        public System.DateTime Login_DT { get; set; }
        public string LoginStatus { get; set; }
        public string IPAddress { get; set; }
    }
}
