//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EN
    {
        public EN()
        {
            this.tblAccount_EN = new HashSet<Account_EN>();
            this.tblFlaggedPostings = new HashSet<FlaggedPosting>();
            this.tblReferrals = new HashSet<Referral>();
        }
    
        public long ENID { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> ActiveAsOf_DT { get; set; }
        public bool ActiveYN { get; set; }
        public Nullable<int> EstimatedTicketHolders { get; set; }
        public string EN_Type { get; set; }
    
        public virtual ICollection<Account_EN> tblAccount_EN { get; set; }
        public virtual ICollection<FlaggedPosting> tblFlaggedPostings { get; set; }
        public virtual ICollection<Referral> tblReferrals { get; set; }
    }
}
