//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FlaggedPosting
    {
        public long FlaggedPostingID { get; set; }
        public long ENID { get; set; }
        public long JobPostingID { get; set; }
        public long Account_ENID { get; set; }
        public long FromAccount_ENID { get; set; }
        public System.DateTime Flagged_DT { get; set; }
    
        public virtual Account_EN tblAccount_EN { get; set; }
        public virtual Account_EN tblAccount_EN1 { get; set; }
        public virtual EN tblEN { get; set; }
        public virtual JobPosting tblJobPosting { get; set; }
    }
}
