//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Industry_Category
    {
        public Industry_Category()
        {
            this.tblLIST_Industry = new HashSet<Industry>();
        }
    
        public string NAIC_Industry_Code { get; set; }
        public string Category_Title { get; set; }
    
        public virtual ICollection<Industry> tblLIST_Industry { get; set; }
    }
}
