//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.tblJobPostings = new HashSet<JobPosting>();
        }
    
        public long LocationID { get; set; }
        public long PartnerID { get; set; }
        public string PartnerLocationCode { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string Zip { get; set; }
        public string Phone1 { get; set; }
        public string Phone2 { get; set; }
        public string Fax { get; set; }
        public bool IsPrimaryLocation_YN { get; set; }
    
        public virtual Partner tblPartner { get; set; }
        public virtual ICollection<JobPosting> tblJobPostings { get; set; }
    }
}
