//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Partner
    {
        public Partner()
        {
            this.tblAccount_Employer = new HashSet<Account_Employer>();
            this.tblContacts = new HashSet<Contact>();
            this.tblJobPostings = new HashSet<JobPosting>();
            this.tblLocations = new HashSet<Location>();
            this.tblPositions = new HashSet<Position>();
            this.tblLINK_Partner_to_Industry = new HashSet<LINK_Partner_to_Industry>();
        }
    
        public long PartnerID { get; set; }
        public string CompanyName { get; set; }
        public Nullable<System.DateTime> ActiveAsOf_DT { get; set; }
        public bool ActiveYN { get; set; }
    
        public virtual ICollection<Account_Employer> tblAccount_Employer { get; set; }
        public virtual ICollection<Contact> tblContacts { get; set; }
        public virtual ICollection<JobPosting> tblJobPostings { get; set; }
        public virtual ICollection<Location> tblLocations { get; set; }
        public virtual ICollection<Position> tblPositions { get; set; }
        public virtual ICollection<LINK_Partner_to_Industry> tblLINK_Partner_to_Industry { get; set; }
    }
}
