//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Position
    {
        public Position()
        {
            this.tblJobPostings = new HashSet<JobPosting>();
            this.tblLIST_Skill = new HashSet<Skill>();
        }
    
        public long PositionID { get; set; }
        public Nullable<long> PartnerID { get; set; }
        public Nullable<long> JobCategoryID { get; set; }
        public string JobTitle { get; set; }
        public string BusinessCategory { get; set; }
        public string Description_External { get; set; }
        public string Description_JobPosting { get; set; }
        public string Requirements { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<JobPosting> tblJobPostings { get; set; }
        public virtual Partner tblPartner { get; set; }
        public virtual ICollection<Skill> tblLIST_Skill { get; set; }
    }
}
