//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralNote
    {
        public long ReferralNoteID { get; set; }
        public long ReferralID { get; set; }
        public long Account_EmployerID { get; set; }
        public string Note { get; set; }
        public bool ProvideAsFeedback_YN { get; set; }
    
        public virtual Account_Employer tblAccount_Employer { get; set; }
        public virtual Referral tblReferral { get; set; }
    }
}
