//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReferralStatus
    {
        public ReferralStatus()
        {
            this.tblReferrals = new HashSet<Referral>();
        }
    
        public int ReferralStatusID { get; set; }
        public string ReferralStatusDesc { get; set; }
    
        public virtual ICollection<Referral> tblReferrals { get; set; }
    }
}
