//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Referral
    {
        public Referral()
        {
            this.tblReferralNotes = new HashSet<ReferralNote>();
        }
    
        public long ReferralID { get; set; }
        public System.DateTime Referral_DT { get; set; }
        public long JobPostingID { get; set; }
        public int ReferralTypeID { get; set; }
        public int ReferralStatusID { get; set; }
        public long Account_ENID { get; set; }
        public long ENID { get; set; }
        public string Name_First { get; set; }
        public string Name_Last { get; set; }
        public string File_CoverLetter { get; set; }
        public string File_Resume { get; set; }
        public string EN_Notes { get; set; }
        public string ConfirmationNumber { get; set; }
    
        public virtual Account_EN tblAccount_EN { get; set; }
        public virtual EN tblEN { get; set; }
        public virtual JobPosting tblJobPosting { get; set; }
        public virtual ReferralStatus tblLIST_ReferralStatus { get; set; }
        public virtual ReferralType tblLIST_ReferralType { get; set; }
        public virtual ICollection<ReferralNote> tblReferralNotes { get; set; }
    }
}
