//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Skill
    {
        public Skill()
        {
            this.tblPositions = new HashSet<Position>();
        }
    
        public long SkillID { get; set; }
        public string SkillName { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<Position> tblPositions { get; set; }
    }
}
