//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ENJobExchange.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblREF_USZipCodes
    {
        public string ZipCode { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public decimal Latitude { get; set; }
        public decimal Longitude { get; set; }
        public decimal GMTOffset { get; set; }
        public bool DaylightSavingsYN { get; set; }
        public int CityZip_Count { get; set; }
    }
}
